---
title: "child2"
output: html_document
---

### RStudio

RStudio includes a variety of features intended to make developing R Markdown websites more productive. These features are available only in the current [Preview Release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio so you should download and install it before trying out the features described below.

#### Website Project

Note that all of the RStudio features for website authoring described below require the use of an RStudio Project tied to your website's directory. See the documentation on [RStudio Projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects) for additional information on how to create and use projects.

#### Individual Pages

As you work on the individual pages of your website you can render them using the **Knit** button just as you do with conventional standalone R Markdown documents:

Knitting an individual page will only render and preview that page, not the other pages in the website.

#### Entire Website

To render all of the pages in the website you use the **Build** pane, which calls `rmarkdown::render_site` to build and then preview the entire site:




#### Supporting Files

RStudio supports "live preview" of changes that you make to supporting files within your website (e.g. CSS, JavaScript, Rmd partials, R scripts, YAML config files, etc.). 

Changes to CSS and JavaScript files always result in a refresh of the currently active page preview. Changes to other files (e.g. shared scripts and config files) trigger a re-knit of the active page preview (this behavior can be disabled via the options dialog available from the Build pane). 

Note that only the active page is re-knit so once you are happy with the results of rendering you should be sure to rebuild the entire site from the **Build** pane to ensure that all pages inherit your changes.

#### Side by Side Preview

When working iteratively on a page you might find it more convenient to preview it side-by-side with the editor rather than in an external window. You can configure RStudio to do this using the options menu on the editor toolbar:


### Command Line

#### Rendering

If you aren't working within RStudio and/or want to build sites from the command line you can call the `render_site` function directly from within the website directory. Pass no arguments to render the entire site or a single file in order to render just that file:

```r
# render the entire site
rmarkdown::render_site()

# render a single file only
rmarkdown::render_site("about.Rmd")
```

#### Cleaning Up

To clean up all of the files generated via `render_site` you can call the `clean_site` function, which will remove all files generated by rendering your site's markdown documents including knitr `_cache` directories. You can specify the `preview = FALSE` option to just list the files to be removed rather than actually removing them:

```r
# list which files will be removed
rmarkdown::clean_site(preview = TRUE)

# actually remove the files
rmarkdown::clean_site()
```

### knitr Caching

If your website is time consuming to render you may want to enable [knitr caching](authoring_rcodechunks.html#caching) during the development of the site so that you can more rapidly preview changes. To enable caching for an individual chunk just add the `cache = TRUE` chunk option:

<pre class="markdown"><code>&#96;&#96;&#96;{r, cache = TRUE}
data <- longComputation()
&#96;&#96;&#96;
</code></pre>

To enable caching for an entire document add `cache = TRUE` to the global chunk option defaults:

<pre class="markdown"><code>&#96;&#96;&#96;{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
&#96;&#96;&#96;
</code></pre>

Note that when knitr caching is enabled for an Rmd it's `_files` directory will be copied rather than moved to the `_site` directory (since the cache requires references to generated figures in the `_files` directory).